version: '3.8'

services:
  neo4j:
    image: neo4j:5.23.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/Password123
    volumes:
      - ./data:/data
    networks:
      - neo4j_network

networks:
  neo4j_network:
    driver: bridge
